application: scapes-uci
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /test.*
  script: gaeunit.application
- url: /stylesheets
  static_dir: stylesheets
- url: /js
  static_dir: js
- url: /pde
  static_dir: pde
- url: /_ah/mail/.+ 
  script: handle_incoming_email.app
  login: admin
- url: /.*
  script: main.app

libraries:
- name: jinja2
  version: latest
- name: setuptools
  version: latest

builtins:
- deferred: on

inbound_services:
- mail
